apiVersion: v1
kind: ConfigMap
metadata:
  name: logback-traceid
  namespace: test
data:
  logback-spring.xml: |
    <configuration scan="true">
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <!-- MDC(trace_id, span_id) 출력 -->
          <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger - %msg trace_id=%X{trace_id} span_id=%X{span_id}%n</pattern>
        </encoder>
      </appender>

      <root level="INFO">
        <appender-ref ref="STDOUT"/>
      </root>
    </configuration>

