kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: app-1-cluster
featureGates:
  # any feature gate can be enabled here with "Name": true
  # or disabled here with "Name": false
  # not all feature gates are tested, however
  "CSIMigration": true
runtimeConfig:
  "api/alpha": "false"
networking:
  ipFamily: ipv6 #dual
  apiServerAddress: 127.0.0.1

  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  #! apiServerAddress: "127.0.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  #! apiServerPort: 6443

  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"

  # the default CNI will not be installed
  disableDefaultCNI: true

  kubeProxyMode: "ipvs"

# multi node cluster
nodes:
  - role: control-plane
  - role: worker
    image: kindest/node:v1.16.4@sha256:b91a2c2317a000f3a783489dfb755064177dbc3a0b2f4147d50f04825d016f55
  - role: worker
  - role: worker
